# Source: sample-web-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sample-web-app
  labels:
    run: sample-web-app
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    run: sample-web-app
---
# Source: sample-web-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: sample-web-app
  name: sample-web-app
spec:
  selector:
    matchLabels:
      run: sample-web-app
  replicas: 1
  template:
    metadata:
      labels:
        run: sample-web-app
    spec:
      containers:
        - name: sample-web-app
          image: IMAGE_REPOSITORY:$BUILD_NUMBER
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 550m
              memory: 800Mi
            requests:
              cpu: 250m
              memory: 600Mi
---
# Source: sample-web-app/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ingress-sample-web-app
spec:
  rules:
    - host: sampleapp.yourcluster.com
      http:
        paths:
          - backend:
              service:
                name: sample-web-app
                port:
                  number: 80
            pathType: ImplementationSpecific
